export enum AnalyticsEvent {
  // Auth
  AUTH_SUCCESS = "AUTH_SUCCESS",
  GET_CTX = "GET_CTX",
  LIST_COMPONENTS = "LIST_COMPONENTS",
  GET_COMPONENTS = "GET_COMPONENTS",
  GET_COMPONENT_PROPS = "GET_COMPONENT_PROPS",
  GET_COMPONENT_EXAMPLES = "GET_COMPONENT_EXAMPLES",
  GET_COMPONENT_DOCS = "GET_COMPONENT_DOCS",
  LIST_DOCS = "LIST_DOCS",
  GET_DOCS = "GET_DOCS",
  GET_DOCS_CONTENT = "GET_DOCS_CONTENT",
  GET_THEMES = "GET_THEMES",
  GET_THEME_VARIABLES = "GET_THEME_VARIABLES",
}

export enum AnalyticsErrorEvent {
  // Auth
  AUTH_FAILED = "AUTH_FAILED",
  AUTH_ERROR = "AUTH_ERROR",
  GET_CTX_ERROR = "GET_CTX_ERROR",
  LIST_COMPONENTS_ERROR = "LIST_COMPONENTS_ERROR",
  GET_COMPONENTS_ERROR = "GET_COMPONENTS_ERROR",
  GET_COMPONENT_PROPS_ERROR = "GET_COMPONENT_PROPS_ERROR",
  GET_COMPONENT_EXAMPLES_ERROR = "GET_COMPONENT_EXAMPLES_ERROR",
  GET_COMPONENT_EXAMPLES_DEPENDENCIES_WARNING = "GET_COMPONENT_EXAMPLES_DEPENDENCIES_WARNING",
  GET_COMPONENT_DOCS_ERROR = "GET_COMPONENT_DOCS_ERROR",
  LIST_DOCS_ERROR = "LIST_DOCS_ERROR",
  GET_DOCS_ERROR = "GET_DOCS_ERROR",
  GET_DOCS_CONTENT_ERROR = "GET_DOCS_CONTENT_ERROR",
  GET_THEMES_ERROR = "GET_THEMES_ERROR",
  GET_THEME_VARIABLES_ERROR = "GET_THEME_VARIABLES_ERROR",
}

export interface AnalyticsProperties {
  endpoint: string;
  responseTime: number;
  apiVersion: "legacy" | "v1";
  [key: string]: unknown;
}
