// Maps legacy gravity-ui icon names to MUI Material Icons (Two Tone) on Iconify
// (the `ic:twotone-*` set from @iconify-json/ic). Used to migrate the icon
// library to MUI two-tone without renaming every call site.
//
// Not mapped (rendered as-is by the online Icon): brand logos (mdi:github,
// ion:logo-apple, devicon:google, logos:expo-icon, simple-icons:googleplay,
// tabler:brand-apple-filled, typcn:social-linkedin, lucide:*) and any unmapped
// gravity-ui icon. Material Icons has no brand logos.
//
// Every target below is validated to exist in @iconify-json/ic.
export const ICON_MAP: Record<string, string> = {
  "arrow-down-to-line": "twotone-download",
  "arrow-left": "twotone-arrow-back",
  "arrow-right": "twotone-arrow-forward",
  "arrow-right-from-square": "twotone-launch",
  "arrow-up": "twotone-arrow-upward",
  "arrow-up-right-from-square": "twotone-open-in-new",
  "arrow-uturn-ccw-left": "twotone-undo",
  "arrow-uturn-cw-right": "twotone-redo",
  at: "twotone-alternate-email",
  bars: "twotone-menu",
  bell: "twotone-notifications",
  bold: "twotone-format-bold",
  book: "twotone-menu-book",
  "book-open": "twotone-auto-stories",
  bookmark: "twotone-bookmark-border",
  "bookmark-fill": "twotone-bookmark",
  box: "twotone-inventory-2",
  brush: "twotone-brush",
  "bucket-paint": "twotone-format-color-fill",
  calendar: "twotone-calendar-today",
  "caret-right": "twotone-arrow-right",
  check: "twotone-check",
  "chevron-down": "twotone-keyboard-arrow-down",
  "chevron-left": "twotone-keyboard-arrow-left",
  "chevron-right": "twotone-keyboard-arrow-right",
  "chevron-up": "twotone-keyboard-arrow-up",
  "chevrons-expand-horizontal": "twotone-unfold-more",
  "chevrons-expand-vertical": "twotone-unfold-more",
  "circle-check": "twotone-check-circle",
  "circle-check-fill": "twotone-check-circle",
  "circle-dashed": "twotone-radio-button-unchecked",
  "circle-dollar": "twotone-monetization-on",
  "circle-exclamation-fill": "twotone-error",
  "circle-fill": "twotone-circle",
  "circle-info": "twotone-info",
  "circle-info-fill": "twotone-info",
  "circle-question": "twotone-help",
  "circle-xmark": "twotone-cancel",
  "circle-xmark-fill": "twotone-cancel",
  "circles-4-diamond": "twotone-dashboard",
  clock: "twotone-schedule",
  code: "twotone-code",
  "code-fork": "twotone-fork-right",
  comment: "twotone-chat-bubble-outline",
  copy: "twotone-content-copy",
  "copy-transparent": "twotone-content-copy",
  ellipsis: "twotone-more-horiz",
  "ellipsis-vertical": "twotone-more-vert",
  envelope: "twotone-email",
  eye: "twotone-visibility",
  "eye-slash": "twotone-visibility-off",
  "floppy-disk": "twotone-save",
  "folder-open": "twotone-folder-open",
  gear: "twotone-settings",
  globe: "twotone-public",
  "hard-drive": "twotone-storage",
  heart: "twotone-favorite-border",
  "heart-fill": "twotone-favorite",
  italic: "twotone-format-italic",
  layers: "twotone-layers",
  "layout-cells-large": "twotone-grid-view",
  "layout-columns-3": "twotone-view-column",
  "list-ul": "twotone-format-list-bulleted",
  "lock-open": "twotone-lock-open",
  microphone: "twotone-mic",
  moon: "twotone-dark-mode",
  paperclip: "twotone-attach-file",
  palette: "twotone-palette",
  "pause-fill": "twotone-pause",
  "pen-line": "twotone-edit",
  pencil: "twotone-edit",
  person: "twotone-person",
  "person-gear": "twotone-manage-accounts",
  persons: "twotone-people",
  picture: "twotone-image",
  pin: "twotone-push-pin",
  "pin-fill": "twotone-push-pin",
  "planet-earth": "twotone-public",
  "play-fill": "twotone-play-arrow",
  "plug-connection": "twotone-electrical-services",
  plus: "twotone-add",
  power: "twotone-power-settings-new",
  "qr-code": "twotone-qr-code",
  rocket: "twotone-rocket-launch",
  scissors: "twotone-content-cut",
  "shopping-bag": "twotone-shopping-bag",
  shuffle: "twotone-shuffle",
  smartphone: "twotone-smartphone",
  sparkles: "twotone-auto-awesome",
  "square-article": "twotone-article",
  "square-plus": "twotone-add-box",
  star: "twotone-star-border",
  "star-fill": "twotone-star",
  strikethrough: "twotone-format-strikethrough",
  sun: "twotone-light-mode",
  terminal: "twotone-terminal",
  "text-align-center": "twotone-format-align-center",
  "text-align-justify": "twotone-format-align-justify",
  "text-align-left": "twotone-format-align-left",
  "text-align-right": "twotone-format-align-right",
  "thumbs-down": "twotone-thumb-down",
  "thumbs-up": "twotone-thumb-up",
  "trash-bin": "twotone-delete",
  tray: "twotone-inbox",
  "triangle-exclamation": "twotone-warning",
  underline: "twotone-format-underlined",
  video: "twotone-videocam",
  xmark: "twotone-close",
};

/**
 * Resolves a legacy gravity-ui icon name (with or without the `gravity-ui:`
 * prefix) to its MUI Material Icons Two Tone equivalent (`ic:twotone-*` body
 * key). Returns undefined when there is no mapping.
 */
export function resolveTwoToneIconName(name: string): string | undefined {
  return ICON_MAP[name.replace(/^gravity-ui:/, "")];
}
